require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/complex_dish_kitchens", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ComplexDishKitchen. As you add validations to ComplexDishKitchen, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ComplexDishKitchen.create! valid_attributes
      get complex_dish_kitchens_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      complex_dish_kitchen = ComplexDishKitchen.create! valid_attributes
      get complex_dish_kitchen_url(complex_dish_kitchen)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_complex_dish_kitchen_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      complex_dish_kitchen = ComplexDishKitchen.create! valid_attributes
      get edit_complex_dish_kitchen_url(complex_dish_kitchen)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ComplexDishKitchen" do
        expect {
          post complex_dish_kitchens_url, params: { complex_dish_kitchen: valid_attributes }
        }.to change(ComplexDishKitchen, :count).by(1)
      end

      it "redirects to the created complex_dish_kitchen" do
        post complex_dish_kitchens_url, params: { complex_dish_kitchen: valid_attributes }
        expect(response).to redirect_to(complex_dish_kitchen_url(ComplexDishKitchen.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ComplexDishKitchen" do
        expect {
          post complex_dish_kitchens_url, params: { complex_dish_kitchen: invalid_attributes }
        }.to change(ComplexDishKitchen, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post complex_dish_kitchens_url, params: { complex_dish_kitchen: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested complex_dish_kitchen" do
        complex_dish_kitchen = ComplexDishKitchen.create! valid_attributes
        patch complex_dish_kitchen_url(complex_dish_kitchen), params: { complex_dish_kitchen: new_attributes }
        complex_dish_kitchen.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the complex_dish_kitchen" do
        complex_dish_kitchen = ComplexDishKitchen.create! valid_attributes
        patch complex_dish_kitchen_url(complex_dish_kitchen), params: { complex_dish_kitchen: new_attributes }
        complex_dish_kitchen.reload
        expect(response).to redirect_to(complex_dish_kitchen_url(complex_dish_kitchen))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        complex_dish_kitchen = ComplexDishKitchen.create! valid_attributes
        patch complex_dish_kitchen_url(complex_dish_kitchen), params: { complex_dish_kitchen: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested complex_dish_kitchen" do
      complex_dish_kitchen = ComplexDishKitchen.create! valid_attributes
      expect {
        delete complex_dish_kitchen_url(complex_dish_kitchen)
      }.to change(ComplexDishKitchen, :count).by(-1)
    end

    it "redirects to the complex_dish_kitchens list" do
      complex_dish_kitchen = ComplexDishKitchen.create! valid_attributes
      delete complex_dish_kitchen_url(complex_dish_kitchen)
      expect(response).to redirect_to(complex_dish_kitchens_url)
    end
  end
end
